version: '3.9'

services:
  db:
    image: postgres:latest
    expose:
      - "5433"
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_DB=knex_test_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    command: -p 5431

  web:
    build: .
    command: bash -c "npm run migrate && npm run start"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      DB_URL: 'postgres://postgres:1234@psql_knex_db_1:5431/knex_test_local'